spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/aps-dsd-air-quality?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${username}
    password: ${password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: false